2025-03-05 11:37:31,777 INFO    StreamThr :64343 [internal.py:wandb_internal():85] W&B internal server running at pid: 64343, started at: 2025-03-05 11:37:31.776983
2025-03-05 11:37:31,779 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status
2025-03-05 11:37:31,784 INFO    WriterThread:64343 [datastore.py:open_for_write():87] open: ./wandb/run-20250305_113731-xlgap1il/run-xlgap1il.wandb
2025-03-05 11:37:31,785 DEBUG   SenderThread:64343 [sender.py:send():379] send: header
2025-03-05 11:37:31,829 DEBUG   SenderThread:64343 [sender.py:send():379] send: run
2025-03-05 11:37:31,830 INFO    SenderThread:64343 [sender.py:_setup_resume():749] checking resume status for None/LSTM-Prediction/xlgap1il
2025-03-05 11:37:32,216 INFO    SenderThread:64343 [dir_watcher.py:__init__():211] watching files in: ./wandb/run-20250305_113731-xlgap1il/files
2025-03-05 11:37:32,216 INFO    SenderThread:64343 [sender.py:_start_run_threads():1188] run started: xlgap1il with start time 1741196251.778576
2025-03-05 11:37:32,226 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: check_version
2025-03-05 11:37:32,226 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: check_version
2025-03-05 11:37:32,394 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: run_start
2025-03-05 11:37:32,408 DEBUG   HandlerThread:64343 [system_info.py:__init__():26] System info init
2025-03-05 11:37:32,408 DEBUG   HandlerThread:64343 [system_info.py:__init__():41] System info init done
2025-03-05 11:37:32,409 INFO    HandlerThread:64343 [system_monitor.py:start():194] Starting system monitor
2025-03-05 11:37:32,409 INFO    SystemMonitor:64343 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-05 11:37:32,409 INFO    HandlerThread:64343 [system_monitor.py:probe():214] Collecting system info
2025-03-05 11:37:32,413 INFO    SystemMonitor:64343 [interfaces.py:start():188] Started cpu monitoring
2025-03-05 11:37:32,416 INFO    SystemMonitor:64343 [interfaces.py:start():188] Started disk monitoring
2025-03-05 11:37:32,418 INFO    SystemMonitor:64343 [interfaces.py:start():188] Started gpuapple monitoring
2025-03-05 11:37:32,420 ERROR   HandlerThread:64343 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:32,420 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:32,420 INFO    SystemMonitor:64343 [interfaces.py:start():188] Started memory monitoring
2025-03-05 11:37:32,423 DEBUG   HandlerThread:64343 [system_info.py:probe():152] Probing system
2025-03-05 11:37:32,424 INFO    SystemMonitor:64343 [interfaces.py:start():188] Started network monitoring
2025-03-05 11:37:32,428 DEBUG   HandlerThread:64343 [system_info.py:_probe_git():137] Probing git
2025-03-05 11:37:32,454 DEBUG   HandlerThread:64343 [system_info.py:_probe_git():145] Probing git done
2025-03-05 11:37:32,455 DEBUG   HandlerThread:64343 [system_info.py:probe():200] Probing system done
2025-03-05 11:37:32,455 DEBUG   HandlerThread:64343 [system_monitor.py:probe():223] {'os': 'macOS-14.4.1-arm64-arm-64bit', 'python': '3.9.19', 'heartbeatAt': '2025-03-05T17:37:32.423781', 'startedAt': '2025-03-05T17:37:31.767704', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/luozisheng/Documents/Zhu_lab/TimeSeriesPrediction/main.py', 'codePathLocal': 'main.py', 'codePath': 'main.py', 'git': {'remote': 'https://github.com/AaronLuo-ai/TimeSeriesSegmentation.git', 'commit': '28dfbe0ba0f264cd994c385e504cdd6f64adbc73'}, 'email': '89952488+AaR0nLu0@users.noreply.github.com', 'root': '/Users/luozisheng/Documents/Zhu_lab/TimeSeriesPrediction', 'host': 'MacBook-Pro-10.local', 'username': 'luozisheng', 'executable': '/Users/luozisheng/miniconda3/envs/seg/bin/python', 'cpu_count': 10, 'cpu_count_logical': 10, 'disk': {'/': {'total': 926.3517189025879, 'used': 431.27109146118164}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2025-03-05 11:37:32,455 INFO    HandlerThread:64343 [system_monitor.py:probe():224] Finished collecting system info
2025-03-05 11:37:32,455 INFO    HandlerThread:64343 [system_monitor.py:probe():227] Publishing system info
2025-03-05 11:37:32,455 DEBUG   HandlerThread:64343 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-03-05 11:37:33,222 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113731-xlgap1il/files/conda-environment.yaml
2025-03-05 11:37:33,772 DEBUG   HandlerThread:64343 [system_info.py:_save_conda():224] Saving conda packages done
2025-03-05 11:37:33,773 INFO    HandlerThread:64343 [system_monitor.py:probe():229] Finished publishing system info
2025-03-05 11:37:33,778 DEBUG   SenderThread:64343 [sender.py:send():379] send: files
2025-03-05 11:37:33,778 INFO    SenderThread:64343 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-03-05 11:37:33,871 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: python_packages
2025-03-05 11:37:33,871 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: python_packages
2025-03-05 11:37:33,872 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: stop_status
2025-03-05 11:37:33,872 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: stop_status
2025-03-05 11:37:33,872 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:34,060 DEBUG   SenderThread:64343 [sender.py:send():379] send: telemetry
2025-03-05 11:37:34,060 DEBUG   SenderThread:64343 [sender.py:send():379] send: telemetry
2025-03-05 11:37:34,061 DEBUG   SenderThread:64343 [sender.py:send():379] send: metric
2025-03-05 11:37:34,061 DEBUG   SenderThread:64343 [sender.py:send():379] send: telemetry
2025-03-05 11:37:34,061 DEBUG   SenderThread:64343 [sender.py:send():379] send: metric
2025-03-05 11:37:34,061 WARNING SenderThread:64343 [sender.py:send_metric():1405] Seen metric with glob (shouldn't happen)
2025-03-05 11:37:34,061 DEBUG   SenderThread:64343 [sender.py:send():379] send: config
2025-03-05 11:37:34,226 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/conda-environment.yaml
2025-03-05 11:37:34,227 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:37:34,227 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113731-xlgap1il/files/wandb-metadata.json
2025-03-05 11:37:34,227 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113731-xlgap1il/files/requirements.txt
2025-03-05 11:37:34,428 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:34,644 INFO    wandb-upload_0:64343 [upload_job.py:push():130] Uploaded file /var/folders/_3/r8lsqq9n4692d4qbqm6prhmw0000gn/T/tmp79uw4xclwandb/qpibrwew-wandb-metadata.json
2025-03-05 11:37:34,878 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:35,880 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:36,236 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:37:36,435 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:36,882 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:37,076 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:37,884 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:38,440 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:38,888 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:39,889 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:40,449 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:41,207 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:42,184 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:42,458 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:42,890 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:43,186 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:44,188 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:44,466 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:45,192 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:46,194 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:46,474 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:47,197 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:47,891 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:48,205 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:48,496 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:48,878 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: stop_status
2025-03-05 11:37:48,878 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: stop_status
2025-03-05 11:37:49,201 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:50,206 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:50,294 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:37:50,511 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:51,208 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:52,211 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:52,529 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:53,039 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:53,215 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:54,218 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:54,544 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:55,224 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:56,227 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:56,560 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:57,235 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:58,237 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:37:58,573 ERROR   gpuapple  :64343 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:37:58,601 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:58,607 DEBUG   SenderThread:64343 [sender.py:send():379] send: exit
2025-03-05 11:37:58,608 INFO    SenderThread:64343 [sender.py:send_exit():586] handling exit code: 1
2025-03-05 11:37:58,608 INFO    SenderThread:64343 [sender.py:send_exit():588] handling runtime: 26
2025-03-05 11:37:58,609 INFO    SenderThread:64343 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-03-05 11:37:58,610 INFO    SenderThread:64343 [sender.py:send_exit():594] send defer
2025-03-05 11:37:58,610 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,610 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 0
2025-03-05 11:37:58,610 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,610 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 0
2025-03-05 11:37:58,610 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 1
2025-03-05 11:37:58,611 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,611 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 1
2025-03-05 11:37:58,611 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,611 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 1
2025-03-05 11:37:58,611 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 2
2025-03-05 11:37:58,611 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,611 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 2
2025-03-05 11:37:58,611 INFO    HandlerThread:64343 [system_monitor.py:finish():203] Stopping system monitor
2025-03-05 11:37:58,611 DEBUG   SystemMonitor:64343 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-05 11:37:58,611 DEBUG   SystemMonitor:64343 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-05 11:37:58,611 DEBUG   SystemMonitor:64343 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-05 11:37:58,611 INFO    HandlerThread:64343 [interfaces.py:finish():200] Joined cpu monitor
2025-03-05 11:37:58,612 INFO    HandlerThread:64343 [interfaces.py:finish():200] Joined disk monitor
2025-03-05 11:37:58,612 INFO    HandlerThread:64343 [interfaces.py:finish():200] Joined gpuapple monitor
2025-03-05 11:37:58,612 INFO    HandlerThread:64343 [interfaces.py:finish():200] Joined memory monitor
2025-03-05 11:37:58,612 INFO    HandlerThread:64343 [interfaces.py:finish():200] Joined network monitor
2025-03-05 11:37:58,612 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,612 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 2
2025-03-05 11:37:58,612 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 3
2025-03-05 11:37:58,612 DEBUG   SenderThread:64343 [sender.py:send():379] send: telemetry
2025-03-05 11:37:58,612 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,612 DEBUG   SenderThread:64343 [sender.py:send():379] send: stats
2025-03-05 11:37:58,612 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 3
2025-03-05 11:37:58,613 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,613 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 3
2025-03-05 11:37:58,613 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 4
2025-03-05 11:37:58,613 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,613 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 4
2025-03-05 11:37:58,613 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,613 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 4
2025-03-05 11:37:58,613 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 5
2025-03-05 11:37:58,613 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,613 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 5
2025-03-05 11:37:58,613 DEBUG   SenderThread:64343 [sender.py:send():379] send: summary
2025-03-05 11:37:58,614 INFO    SenderThread:64343 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-03-05 11:37:58,614 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,614 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 5
2025-03-05 11:37:58,614 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 6
2025-03-05 11:37:58,614 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,614 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 6
2025-03-05 11:37:58,614 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,614 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 6
2025-03-05 11:37:58,617 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:37:58,749 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 7
2025-03-05 11:37:58,749 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:37:58,749 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 7
2025-03-05 11:37:58,749 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:37:58,749 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 7
2025-03-05 11:37:59,339 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/config.yaml
2025-03-05 11:37:59,339 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113731-xlgap1il/files/wandb-summary.json
2025-03-05 11:37:59,614 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:00,346 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:38:01,931 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 8
2025-03-05 11:38:01,932 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:01,932 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:01,933 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 8
2025-03-05 11:38:01,933 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:01,933 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 8
2025-03-05 11:38:01,933 INFO    SenderThread:64343 [job_builder.py:build():440] Attempting to build job artifact
2025-03-05 11:38:01,934 INFO    SenderThread:64343 [job_builder.py:_get_source_type():569] is repo sourced job
2025-03-05 11:38:02,137 INFO    SenderThread:64343 [job_builder.py:build():545] adding wandb-job metadata file
2025-03-05 11:38:02,165 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 9
2025-03-05 11:38:02,165 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:02,165 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 9
2025-03-05 11:38:02,165 DEBUG   SenderThread:64343 [sender.py:send():379] send: artifact
2025-03-05 11:38:02,355 INFO    Thread-12 :64343 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:38:02,628 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:02,929 INFO    wandb-upload_0:64343 [upload_job.py:push():88] Uploaded file /Users/luozisheng/Library/Application Support/wandb/artifacts/staging/tmp5ow2iebl
2025-03-05 11:38:03,143 INFO    wandb-upload_1:64343 [upload_job.py:push():88] Uploaded file /var/folders/_3/r8lsqq9n4692d4qbqm6prhmw0000gn/T/tmpaqgl9v00/wandb-job.json
2025-03-05 11:38:04,713 INFO    SenderThread:64343 [sender.py:send_artifact():1530] sent artifact job-https___github.com_AaronLuo-ai_TimeSeriesSegmentation.git_main.py - {'id': 'QXJ0aWZhY3Q6MTU0ODEwNTEzMQ==', 'state': 'PENDING', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjU3NDMwMzcyMQ==', 'latestArtifact': None}}
2025-03-05 11:38:04,714 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:04,714 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:04,714 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 9
2025-03-05 11:38:04,714 INFO    SenderThread:64343 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-05 11:38:05,374 INFO    SenderThread:64343 [dir_watcher.py:finish():388] scan: ./wandb/run-20250305_113731-xlgap1il/files
2025-03-05 11:38:05,375 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/requirements.txt requirements.txt
2025-03-05 11:38:05,376 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/output.log output.log
2025-03-05 11:38:05,376 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/config.yaml config.yaml
2025-03-05 11:38:05,377 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/wandb-summary.json wandb-summary.json
2025-03-05 11:38:05,385 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/conda-environment.yaml conda-environment.yaml
2025-03-05 11:38:05,391 INFO    SenderThread:64343 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113731-xlgap1il/files/wandb-metadata.json wandb-metadata.json
2025-03-05 11:38:05,392 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 10
2025-03-05 11:38:05,392 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:05,392 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:05,393 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 10
2025-03-05 11:38:05,393 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:05,393 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 10
2025-03-05 11:38:05,393 INFO    SenderThread:64343 [file_pusher.py:finish():169] shutting down file pusher
2025-03-05 11:38:05,642 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:05,643 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:05,793 INFO    wandb-upload_0:64343 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113731-xlgap1il/files/output.log
2025-03-05 11:38:05,826 INFO    wandb-upload_2:64343 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113731-xlgap1il/files/requirements.txt
2025-03-05 11:38:06,056 INFO    wandb-upload_1:64343 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113731-xlgap1il/files/config.yaml
2025-03-05 11:38:06,065 INFO    wandb-upload_3:64343 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113731-xlgap1il/files/wandb-summary.json
2025-03-05 11:38:06,068 INFO    wandb-upload_4:64343 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113731-xlgap1il/files/conda-environment.yaml
2025-03-05 11:38:06,273 INFO    Thread-11 :64343 [sender.py:transition_state():614] send defer: 11
2025-03-05 11:38:06,274 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:06,274 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 11
2025-03-05 11:38:06,274 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:06,275 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 11
2025-03-05 11:38:06,275 INFO    SenderThread:64343 [file_pusher.py:join():175] waiting for file pusher
2025-03-05 11:38:06,276 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 12
2025-03-05 11:38:06,276 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:06,276 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 12
2025-03-05 11:38:06,276 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:06,276 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 12
2025-03-05 11:38:06,276 INFO    SenderThread:64343 [file_stream.py:finish():601] file stream finish called
2025-03-05 11:38:06,348 INFO    SenderThread:64343 [file_stream.py:finish():605] file stream finish is done
2025-03-05 11:38:06,348 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 13
2025-03-05 11:38:06,348 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:06,348 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 13
2025-03-05 11:38:06,348 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:06,348 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 13
2025-03-05 11:38:06,349 INFO    SenderThread:64343 [sender.py:transition_state():614] send defer: 14
2025-03-05 11:38:06,349 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:06,349 INFO    HandlerThread:64343 [handler.py:handle_request_defer():184] handle defer: 14
2025-03-05 11:38:06,349 DEBUG   SenderThread:64343 [sender.py:send():379] send: final
2025-03-05 11:38:06,349 DEBUG   SenderThread:64343 [sender.py:send():379] send: footer
2025-03-05 11:38:06,350 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:06,350 INFO    SenderThread:64343 [sender.py:send_request_defer():610] handle sender defer: 14
2025-03-05 11:38:06,351 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:06,351 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: server_info
2025-03-05 11:38:06,352 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:06,352 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: get_summary
2025-03-05 11:38:06,353 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:06,353 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: sampled_history
2025-03-05 11:38:06,353 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: server_info
2025-03-05 11:38:06,353 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:06,420 DEBUG   SenderThread:64343 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:06,420 INFO    MainThread:64343 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2025-03-05 11:38:06,420 INFO    MainThread:64343 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2025-03-05 11:38:06,421 INFO    MainThread:64343 [wandb_run.py:_footer_sync_info():3950] logging synced files
2025-03-05 11:38:06,421 DEBUG   HandlerThread:64343 [handler.py:handle_request():158] handle_request: shutdown
2025-03-05 11:38:06,422 INFO    HandlerThread:64343 [handler.py:finish():882] shutting down handler
2025-03-05 11:38:07,358 INFO    WriterThread:64343 [datastore.py:close():296] close: ./wandb/run-20250305_113731-xlgap1il/run-xlgap1il.wandb
2025-03-05 11:38:07,425 INFO    SenderThread:64343 [sender.py:finish():1608] shutting down sender
2025-03-05 11:38:07,426 INFO    SenderThread:64343 [file_pusher.py:finish():169] shutting down file pusher
2025-03-05 11:38:07,426 INFO    SenderThread:64343 [file_pusher.py:join():175] waiting for file pusher
