2025-03-05 11:38:34,845 INFO    StreamThr :64451 [internal.py:wandb_internal():85] W&B internal server running at pid: 64451, started at: 2025-03-05 11:38:34.844727
2025-03-05 11:38:34,847 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status
2025-03-05 11:38:34,854 INFO    WriterThread:64451 [datastore.py:open_for_write():87] open: ./wandb/run-20250305_113834-t9nd4s6c/run-t9nd4s6c.wandb
2025-03-05 11:38:34,854 DEBUG   SenderThread:64451 [sender.py:send():379] send: header
2025-03-05 11:38:34,904 DEBUG   SenderThread:64451 [sender.py:send():379] send: run
2025-03-05 11:38:34,905 INFO    SenderThread:64451 [sender.py:_setup_resume():749] checking resume status for None/LSTM-Prediction/t9nd4s6c
2025-03-05 11:38:35,587 INFO    SenderThread:64451 [dir_watcher.py:__init__():211] watching files in: ./wandb/run-20250305_113834-t9nd4s6c/files
2025-03-05 11:38:35,587 INFO    SenderThread:64451 [sender.py:_start_run_threads():1188] run started: t9nd4s6c with start time 1741196314.846265
2025-03-05 11:38:35,597 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: check_version
2025-03-05 11:38:35,597 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: check_version
2025-03-05 11:38:35,784 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: run_start
2025-03-05 11:38:35,797 DEBUG   HandlerThread:64451 [system_info.py:__init__():26] System info init
2025-03-05 11:38:35,797 DEBUG   HandlerThread:64451 [system_info.py:__init__():41] System info init done
2025-03-05 11:38:35,797 INFO    HandlerThread:64451 [system_monitor.py:start():194] Starting system monitor
2025-03-05 11:38:35,797 INFO    SystemMonitor:64451 [system_monitor.py:_start():158] Starting system asset monitoring threads
2025-03-05 11:38:35,798 INFO    HandlerThread:64451 [system_monitor.py:probe():214] Collecting system info
2025-03-05 11:38:35,801 INFO    SystemMonitor:64451 [interfaces.py:start():188] Started cpu monitoring
2025-03-05 11:38:35,804 INFO    SystemMonitor:64451 [interfaces.py:start():188] Started disk monitoring
2025-03-05 11:38:35,804 ERROR   HandlerThread:64451 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:35,807 INFO    SystemMonitor:64451 [interfaces.py:start():188] Started gpuapple monitoring
2025-03-05 11:38:35,808 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:35,811 DEBUG   HandlerThread:64451 [system_info.py:probe():152] Probing system
2025-03-05 11:38:35,812 INFO    SystemMonitor:64451 [interfaces.py:start():188] Started memory monitoring
2025-03-05 11:38:35,813 INFO    SystemMonitor:64451 [interfaces.py:start():188] Started network monitoring
2025-03-05 11:38:35,817 DEBUG   HandlerThread:64451 [system_info.py:_probe_git():137] Probing git
2025-03-05 11:38:35,843 DEBUG   HandlerThread:64451 [system_info.py:_probe_git():145] Probing git done
2025-03-05 11:38:35,844 DEBUG   HandlerThread:64451 [system_info.py:probe():200] Probing system done
2025-03-05 11:38:35,844 DEBUG   HandlerThread:64451 [system_monitor.py:probe():223] {'os': 'macOS-14.4.1-arm64-arm-64bit', 'python': '3.9.19', 'heartbeatAt': '2025-03-05T17:38:35.812646', 'startedAt': '2025-03-05T17:38:34.833834', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/luozisheng/Documents/Zhu_lab/TimeSeriesPrediction/main.py', 'codePathLocal': 'main.py', 'codePath': 'main.py', 'git': {'remote': 'https://github.com/AaronLuo-ai/TimeSeriesSegmentation.git', 'commit': '28dfbe0ba0f264cd994c385e504cdd6f64adbc73'}, 'email': '89952488+AaR0nLu0@users.noreply.github.com', 'root': '/Users/luozisheng/Documents/Zhu_lab/TimeSeriesPrediction', 'host': 'MacBook-Pro-10.local', 'username': 'luozisheng', 'executable': '/Users/luozisheng/miniconda3/envs/seg/bin/python', 'cpu_count': 10, 'cpu_count_logical': 10, 'disk': {'/': {'total': 926.3517189025879, 'used': 431.27492904663086}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2025-03-05 11:38:35,844 INFO    HandlerThread:64451 [system_monitor.py:probe():224] Finished collecting system info
2025-03-05 11:38:35,844 INFO    HandlerThread:64451 [system_monitor.py:probe():227] Publishing system info
2025-03-05 11:38:35,844 DEBUG   HandlerThread:64451 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2025-03-05 11:38:36,593 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113834-t9nd4s6c/files/conda-environment.yaml
2025-03-05 11:38:37,274 DEBUG   HandlerThread:64451 [system_info.py:_save_conda():224] Saving conda packages done
2025-03-05 11:38:37,276 INFO    HandlerThread:64451 [system_monitor.py:probe():229] Finished publishing system info
2025-03-05 11:38:37,284 DEBUG   SenderThread:64451 [sender.py:send():379] send: files
2025-03-05 11:38:37,284 INFO    SenderThread:64451 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2025-03-05 11:38:37,396 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: python_packages
2025-03-05 11:38:37,396 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: python_packages
2025-03-05 11:38:37,397 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:37,397 DEBUG   SenderThread:64451 [sender.py:send():379] send: telemetry
2025-03-05 11:38:37,398 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: stop_status
2025-03-05 11:38:37,398 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: stop_status
2025-03-05 11:38:37,554 DEBUG   SenderThread:64451 [sender.py:send():379] send: telemetry
2025-03-05 11:38:37,554 DEBUG   SenderThread:64451 [sender.py:send():379] send: metric
2025-03-05 11:38:37,554 DEBUG   SenderThread:64451 [sender.py:send():379] send: telemetry
2025-03-05 11:38:37,554 DEBUG   SenderThread:64451 [sender.py:send():379] send: metric
2025-03-05 11:38:37,555 WARNING SenderThread:64451 [sender.py:send_metric():1405] Seen metric with glob (shouldn't happen)
2025-03-05 11:38:37,555 DEBUG   SenderThread:64451 [sender.py:send():379] send: config
2025-03-05 11:38:37,593 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/conda-environment.yaml
2025-03-05 11:38:37,593 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113834-t9nd4s6c/files/requirements.txt
2025-03-05 11:38:37,593 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113834-t9nd4s6c/files/wandb-metadata.json
2025-03-05 11:38:37,593 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:38:37,818 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:38,029 INFO    wandb-upload_0:64451 [upload_job.py:push():130] Uploaded file /var/folders/_3/r8lsqq9n4692d4qbqm6prhmw0000gn/T/tmpdyciodfmwandb/nv0pqx9u-wandb-metadata.json
2025-03-05 11:38:38,402 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:39,405 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:39,600 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:38:39,823 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:40,408 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:40,564 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:41,411 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:41,830 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:42,413 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:43,415 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:43,838 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:44,419 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:45,422 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:45,847 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:46,417 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:46,428 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:47,428 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:47,853 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:48,435 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:49,438 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:49,862 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:50,440 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:51,443 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:51,846 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:51,868 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:52,402 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: stop_status
2025-03-05 11:38:52,402 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: stop_status
2025-03-05 11:38:52,445 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:53,459 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:53,666 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:38:53,884 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:54,462 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:55,466 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:55,900 ERROR   gpuapple  :64451 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/luozisheng/miniconda3/envs/seg/lib/python3.9/site-packages/wandb/bin/apple_gpu_stats'
2025-03-05 11:38:56,472 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:38:56,903 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:56,908 DEBUG   SenderThread:64451 [sender.py:send():379] send: exit
2025-03-05 11:38:56,908 INFO    SenderThread:64451 [sender.py:send_exit():586] handling exit code: 1
2025-03-05 11:38:56,909 INFO    SenderThread:64451 [sender.py:send_exit():588] handling runtime: 21
2025-03-05 11:38:56,909 INFO    SenderThread:64451 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-03-05 11:38:56,909 INFO    SenderThread:64451 [sender.py:send_exit():594] send defer
2025-03-05 11:38:56,910 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,910 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 0
2025-03-05 11:38:56,910 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,910 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 0
2025-03-05 11:38:56,910 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 1
2025-03-05 11:38:56,910 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,910 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 1
2025-03-05 11:38:56,910 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,910 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 1
2025-03-05 11:38:56,910 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 2
2025-03-05 11:38:56,910 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,910 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 2
2025-03-05 11:38:56,910 INFO    HandlerThread:64451 [system_monitor.py:finish():203] Stopping system monitor
2025-03-05 11:38:56,910 DEBUG   SystemMonitor:64451 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2025-03-05 11:38:56,910 INFO    HandlerThread:64451 [interfaces.py:finish():200] Joined cpu monitor
2025-03-05 11:38:56,910 DEBUG   SystemMonitor:64451 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2025-03-05 11:38:56,911 INFO    HandlerThread:64451 [interfaces.py:finish():200] Joined disk monitor
2025-03-05 11:38:56,911 DEBUG   SystemMonitor:64451 [system_monitor.py:_start():183] Publishing last batch of metrics
2025-03-05 11:38:56,911 INFO    HandlerThread:64451 [interfaces.py:finish():200] Joined gpuapple monitor
2025-03-05 11:38:56,911 INFO    HandlerThread:64451 [interfaces.py:finish():200] Joined memory monitor
2025-03-05 11:38:56,911 INFO    HandlerThread:64451 [interfaces.py:finish():200] Joined network monitor
2025-03-05 11:38:56,912 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 2
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 3
2025-03-05 11:38:56,912 DEBUG   SenderThread:64451 [sender.py:send():379] send: telemetry
2025-03-05 11:38:56,912 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,912 DEBUG   SenderThread:64451 [sender.py:send():379] send: stats
2025-03-05 11:38:56,912 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 3
2025-03-05 11:38:56,912 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 3
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 4
2025-03-05 11:38:56,912 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,912 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 4
2025-03-05 11:38:56,912 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 4
2025-03-05 11:38:56,912 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 5
2025-03-05 11:38:56,913 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,913 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 5
2025-03-05 11:38:56,913 DEBUG   SenderThread:64451 [sender.py:send():379] send: summary
2025-03-05 11:38:56,913 INFO    SenderThread:64451 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2025-03-05 11:38:56,913 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,913 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 5
2025-03-05 11:38:56,913 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 6
2025-03-05 11:38:56,913 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,913 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 6
2025-03-05 11:38:56,913 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,913 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 6
2025-03-05 11:38:56,917 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:38:56,994 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 7
2025-03-05 11:38:56,994 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:56,994 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 7
2025-03-05 11:38:56,994 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:56,995 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 7
2025-03-05 11:38:57,683 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/config.yaml
2025-03-05 11:38:57,683 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:38:57,683 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20250305_113834-t9nd4s6c/files/wandb-summary.json
2025-03-05 11:38:57,913 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:38:59,311 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 8
2025-03-05 11:38:59,312 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:38:59,312 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:59,313 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 8
2025-03-05 11:38:59,313 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:59,313 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 8
2025-03-05 11:38:59,313 INFO    SenderThread:64451 [job_builder.py:build():440] Attempting to build job artifact
2025-03-05 11:38:59,314 INFO    SenderThread:64451 [job_builder.py:_get_source_type():569] is repo sourced job
2025-03-05 11:38:59,488 INFO    SenderThread:64451 [job_builder.py:build():545] adding wandb-job metadata file
2025-03-05 11:38:59,490 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 9
2025-03-05 11:38:59,491 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:38:59,491 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 9
2025-03-05 11:38:59,491 DEBUG   SenderThread:64451 [sender.py:send():379] send: artifact
2025-03-05 11:38:59,694 INFO    Thread-12 :64451 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:38:59,854 INFO    SenderThread:64451 [sender.py:send_artifact():1530] sent artifact job-https___github.com_AaronLuo-ai_TimeSeriesSegmentation.git_main.py - {'id': 'QXJ0aWZhY3Q6MTU0ODEwNTEzMQ==', 'state': 'COMMITTED', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjU3NDMwMzcyMQ==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6MTU0ODEwNTEzMQ==', 'versionIndex': 0}}}
2025-03-05 11:38:59,854 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:38:59,855 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 9
2025-03-05 11:38:59,855 INFO    SenderThread:64451 [dir_watcher.py:finish():358] shutting down directory watcher
2025-03-05 11:38:59,925 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:39:00,699 INFO    SenderThread:64451 [dir_watcher.py:finish():388] scan: ./wandb/run-20250305_113834-t9nd4s6c/files
2025-03-05 11:39:00,700 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/requirements.txt requirements.txt
2025-03-05 11:39:00,700 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/output.log output.log
2025-03-05 11:39:00,704 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/config.yaml config.yaml
2025-03-05 11:39:00,705 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/wandb-summary.json wandb-summary.json
2025-03-05 11:39:00,708 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/conda-environment.yaml conda-environment.yaml
2025-03-05 11:39:00,709 INFO    SenderThread:64451 [dir_watcher.py:finish():402] scan save: ./wandb/run-20250305_113834-t9nd4s6c/files/wandb-metadata.json wandb-metadata.json
2025-03-05 11:39:00,709 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 10
2025-03-05 11:39:00,709 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:39:00,709 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:39:00,709 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 10
2025-03-05 11:39:00,709 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:39:00,709 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 10
2025-03-05 11:39:00,709 INFO    SenderThread:64451 [file_pusher.py:finish():169] shutting down file pusher
2025-03-05 11:39:00,930 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:39:00,930 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:39:01,109 INFO    wandb-upload_0:64451 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113834-t9nd4s6c/files/requirements.txt
2025-03-05 11:39:01,376 INFO    wandb-upload_1:64451 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113834-t9nd4s6c/files/output.log
2025-03-05 11:39:01,377 INFO    wandb-upload_4:64451 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113834-t9nd4s6c/files/conda-environment.yaml
2025-03-05 11:39:01,402 INFO    wandb-upload_3:64451 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113834-t9nd4s6c/files/wandb-summary.json
2025-03-05 11:39:01,936 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: status_report
2025-03-05 11:39:01,937 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:39:01,937 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:39:01,992 INFO    wandb-upload_2:64451 [upload_job.py:push():130] Uploaded file ./wandb/run-20250305_113834-t9nd4s6c/files/config.yaml
2025-03-05 11:39:02,197 INFO    Thread-11 :64451 [sender.py:transition_state():614] send defer: 11
2025-03-05 11:39:02,197 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:39:02,197 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 11
2025-03-05 11:39:02,198 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:39:02,198 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 11
2025-03-05 11:39:02,198 INFO    SenderThread:64451 [file_pusher.py:join():175] waiting for file pusher
2025-03-05 11:39:02,198 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 12
2025-03-05 11:39:02,199 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:39:02,199 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 12
2025-03-05 11:39:02,199 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:39:02,199 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 12
2025-03-05 11:39:02,199 INFO    SenderThread:64451 [file_stream.py:finish():601] file stream finish called
2025-03-05 11:39:02,281 INFO    SenderThread:64451 [file_stream.py:finish():605] file stream finish is done
2025-03-05 11:39:02,281 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 13
2025-03-05 11:39:02,281 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:39:02,282 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 13
2025-03-05 11:39:02,282 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:39:02,282 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 13
2025-03-05 11:39:02,282 INFO    SenderThread:64451 [sender.py:transition_state():614] send defer: 14
2025-03-05 11:39:02,282 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: defer
2025-03-05 11:39:02,282 INFO    HandlerThread:64451 [handler.py:handle_request_defer():184] handle defer: 14
2025-03-05 11:39:02,282 DEBUG   SenderThread:64451 [sender.py:send():379] send: final
2025-03-05 11:39:02,282 DEBUG   SenderThread:64451 [sender.py:send():379] send: footer
2025-03-05 11:39:02,283 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: defer
2025-03-05 11:39:02,283 INFO    SenderThread:64451 [sender.py:send_request_defer():610] handle sender defer: 14
2025-03-05 11:39:02,283 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:39:02,283 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:39:02,284 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: server_info
2025-03-05 11:39:02,284 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: poll_exit
2025-03-05 11:39:02,284 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: server_info
2025-03-05 11:39:02,285 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: get_summary
2025-03-05 11:39:02,286 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: sampled_history
2025-03-05 11:39:02,286 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: internal_messages
2025-03-05 11:39:02,341 DEBUG   SenderThread:64451 [sender.py:send_request():406] send_request: poll_exit
2025-03-05 11:39:02,341 INFO    MainThread:64451 [wandb_run.py:_footer_history_summary_info():3991] rendering history
2025-03-05 11:39:02,341 INFO    MainThread:64451 [wandb_run.py:_footer_history_summary_info():4023] rendering summary
2025-03-05 11:39:02,341 INFO    MainThread:64451 [wandb_run.py:_footer_sync_info():3950] logging synced files
2025-03-05 11:39:02,342 DEBUG   HandlerThread:64451 [handler.py:handle_request():158] handle_request: shutdown
2025-03-05 11:39:02,342 INFO    HandlerThread:64451 [handler.py:finish():882] shutting down handler
2025-03-05 11:39:03,289 INFO    WriterThread:64451 [datastore.py:close():296] close: ./wandb/run-20250305_113834-t9nd4s6c/run-t9nd4s6c.wandb
2025-03-05 11:39:03,347 INFO    SenderThread:64451 [sender.py:finish():1608] shutting down sender
2025-03-05 11:39:03,348 INFO    SenderThread:64451 [file_pusher.py:finish():169] shutting down file pusher
2025-03-05 11:39:03,348 INFO    SenderThread:64451 [file_pusher.py:join():175] waiting for file pusher
